version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
     - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: .devcontainer/Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - ./api:/home/vscode
    user: vscode
    working_dir: /home/vscode
    command: ["flask", "run", "--host", "0.0.0.0"]

  gui:
    build: ./gui
    ports:
     - "3000:3000"
    volumes:
     - ./gui/src:/app/src
     - ./gui/public:/app/public
