version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
  api:
    build: ./api
    ports:
     - "5000:5000"
     - "5555:5555"
    volumes:
     - ./api/src:/app/src
  gui:
    build: ./gui
    ports:
     - "3000:3000"
    volumes:
     - ./gui/src:/app/src
     - ./gui/public:/app/public
